/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ExamplePalette: typeof import('./src/components/example-palette.vue')['default']
    GlobalPageShell: typeof import('./src/components/GlobalPageShell.vue')['default']
    HeadingsTree: typeof import('./src/components/headings-tree.vue')['default']
    HeadingsTreeNode: typeof import('./src/components/headings-tree-node.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    ListMenu: typeof import('./src/components/list-menu.vue')['default']
    TestPalette: typeof import('./src/components/test-palette.vue')['default']
    Vote: typeof import('./src/components/vote.vue')['default']
  }
}
